export const TODO_ADD_ITEM = 'TODO_ADD_ITEM';
export const TODO_TOGGLE_ITEM = 'TODO_TOGGLE_ITEM';
export const TODO_FILTER = 'TODO_FILTER';

export const TODO_SHOW_ALL = 'TODO_SHOW_ALL';
export const TODO_SHOW_ACTIVE = 'TODO_SHOW_ACTIVE';
export const TODO_SHOW_COMPLETE = 'TODO_SHOW_COMPLETE';
