export const TODO_ADD_ITEM = 'TODO_ADD_ITEM';
export const TODO_DELETE_ITEM = 'TODO_DELETE_ITEM';
export const TODO_TOGGLE_STATUS = 'TODO_TOGGLE_STATUS';
export const TODO_TABS_CHANGE = 'TODO_TABS_CHANGE';
export const TODO_PAGE_CHANGE = 'TODO_PAGE_CHANGE';
export const TODO_SHOW_LOADING = 'TODO_SHOW_LOADING';
export const TODO_UPDATE_LIST = 'TODO_UPDATE_LIST';

export const TODO_FILTER_ALL = 'all';
export const TODO_FILTER_ACTIVATED = 'activated';
export const TODO_FILTER_COMPLETED = 'completed';

export const TODO_FETCH_ERROR = 'TODO_FETCH_ERROR';
export const TODO_FETCH_ADD_ITEM = 'TODO_FETCH_ADD_ITEM';
export const TODO_FETCH_LOAD_LIST = 'TODO_FETCH_LOAD_LIST';
export const TODO_FETCH_SEARCH_LIST = 'TODO_FETCH_SEARCH_LIST';
